name: 'Unity Installer'
author: 'Aytuğ HAN'
description: 'GitHub action to download and install Unity'

inputs:
  unity-version:
    description: Unity version of the project. If not provided it will be automatically fetched from ProjectSettings.asset
    required: false
  unity-version-changeset:
    description: Unity Version Changeset of the project. If not provided automatically parsed from Unity site
    required: false
  unity-modules:
    description: |
      Available modules:
        Documentation: documentation
        Standard Assets: standardassets
        Example Project: example
        Android Build Support: android
        iOS Build Support: ios
        tvOS Build Support: appletv
        Linux Build Support: linux-mono
        SamsungTV Build Support: samsung
        Tizen Build Support: tizen
        WebGL Build Support: webgl
        Windows Build Support: windows
        Facebook Gameroom Build Support: facebook-games
        MonoDevelop / Unity Debugger: monodevelop
        Vuforia Augmented Reality Support: vuforia-ar
        Language packs: language-ja, language-ko, language-zh-cn, language-zh-hant, language-zh-hans
        Mac Build Support (IL2CPP): mac-il2cpp
        Windows Build Support (Mono): windows-mono
        Android SDK & NDK Tools: android-sdk-ndk-tools
        OpenJDK: android-open-jdk
        Lumin OS (Magic Leap) Build Support: lumin
    required: false
  unity-modules-child:
    description: Automatically installs all child modules of selected modules
    required: false
    default: 'true'
  project-path:
    description: Path to Unity project. It will be used to find Unity version
    required: false
    default: ${{ github.workspace }}
  is-self-hosted:
    description: This will prevent invoking commands as sudo
    required: false
    default: 'false'
  unity-activate-license:
    description: This will prevent invoking commands as sudo
    required: false
    default: 'false'
  unity-username:
    description: This is required for license activation
    required: false
  unity-password:
    description: This is required for license activation
    required: false
  unity-serial:
    description: This is required for license activation
    required: false
outputs:
  unity-version:
    description: Unity Version
  unity-path:
    description: Unity Path

runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'lib/return-license.js'

branding:
  icon: archive
  color: orange
